package seleniumjava;

import Model.Alumno;

public class TableReader {
	public static void main(String[] args) {
		TableReaderUtilities reader = new TableReaderUtilities();
		Alumno alumno = reader.getAlumnoNotes("<html xmlns=\"http://www.w3.org/1999/xhtml\"><head id=\"Head1\"><link href=\"../../App_Themes/Granite/_vti_cnf/Default.css\" type=\"text/css\" rel=\"stylesheet\"><link href=\"../../App_Themes/Granite/Default.css\" type=\"text/css\" rel=\"stylesheet\"><title>\r\n" + 
				"	Kardex\r\n" + 
				"</title></head>\r\n" + 
				"<body>\r\n" + 
				"    <div style=\"background-color: White\">\r\n" + 
				"    <br>\r\n" + 
				"    <span id=\"Lbl_Kardex\"><style>\r\n" + 
				"			                  table.bottomBorder{background-color:WhiteSmoke;font-size:xx-small;text-align:center;border-collapse:collapse;}\r\n" + 
				"							  table.bottomBorder td {border-bottom: 1px solid TEAL;padding:1px;}\r\n" + 
				"							</style><center>\r\n" + 
				"								<table width=\"100%\" class=\"bottomBorder\">\r\n" + 
				"									<tbody>\r\n" + 
				"										<tr><td colspan=\"6\" style=\"background-color: Maroon; font-size: x-small; font-weight: bold; color: White; text-align: center\">PRIMER SEMESTRE</td></tr><tr style=\"background-color: WhiteSmoke; font-size: xx-small; text-align: center; font-weight: bold;\"><td width=\"10px\">Clave</td><td width=\"150px\">Materia</td><td width=\"40px\">Fecha</td><td width=\"10px\">Periodo</td><td width=\"10px\">Forma Eval.</td><td width=\"10px\">Calificacion</td></tr><tr><td>R101</td><td align=\"left\">TECNOLOGIAS DE INFORMACION Y COMUNICACION</td><td>Jun 18 2010</td><td>10/2</td><td>ORD</td><td>10</td></tr><tr><td>R102</td><td align=\"left\">COMUNICACION ORAL Y ESCRITA</td><td>Dic 18 2009</td><td>10/1</td><td>ORD</td><td>10</td></tr><tr><td>R103</td><td align=\"left\">SOLUCION DE PROBLEMAS Y CREATIVIDAD</td><td>Jun 18 2010</td><td>10/2</td><td>ORD</td><td>10</td></tr><tr><td>R104</td><td align=\"left\">DESARROLLO SUSTENTABLE</td><td>Jun 18 2010</td><td>10/2</td><td>ORD</td><td>8</td></tr><tr><td>R105</td><td align=\"left\">FUNDAMENTOS DE ADMINISTRACION</td><td>Jun 18 2010</td><td>10/2</td><td>ORD</td><td>9</td></tr><tr><td>R106</td><td align=\"left\">FUNDAMENTOS DE ECONOMÍA</td><td>Jun 18 2010</td><td>10/2</td><td>ORD</td><td>9</td></tr><tr><td>R107</td><td align=\"left\">MATEMÁTICAS PARA NEGOCIOS</td><td>Dic 18 2009</td><td>10/1</td><td>ORD</td><td>8</td></tr><tr><td>R108</td><td align=\"left\">FUNDAMENTOS DE DERECHO</td><td>Dic 18 2009</td><td>10/1</td><td>ORD</td><td>8</td></tr><tr><td>R109</td><td align=\"left\">FUNDAMENTOS DE CONTABILIDAD</td><td>Dic 18 2009</td><td>10/1</td><td>ORD</td><td>10</td></tr><tr><td>R110</td><td align=\"left\">FUNDAMENTOS DE MERCADOTECNIA</td><td>Dic 18 2009</td><td>10/1</td><td>ORD</td><td>9</td></tr><tr><td>R111</td><td align=\"left\">SEMINARIO DE INVESTIGACIÓN</td><td>Jun 18 2010</td><td>10/2</td><td>ORD</td><td>9</td></tr><tr><td>R112</td><td align=\"left\">FUNDAMENTOS DE COMPORTAMIENTO ORGANIZACIONAL</td><td>Dic 18 2009</td><td>10/1</td><td>ORD</td><td>8</td></tr></tbody>\r\n" + 
				"							</table><br></center><style>\r\n" + 
				"			                  table.bottomBorder{background-color:WhiteSmoke;font-size:xx-small;text-align:center;border-collapse:collapse;}\r\n" + 
				"							  table.bottomBorder td {border-bottom: 1px solid TEAL;padding:1px;}\r\n" + 
				"							</style><center>\r\n" + 
				"								<table width=\"100%\" class=\"bottomBorder\"><tbody><tr><td colspan=\"6\" style=\"background-color: Maroon; font-size: x-small; font-weight: bold; color: White; text-align: center\">SEGUNDO SEMESTRE</td></tr><tr style=\"background-color: WhiteSmoke; font-size: xx-small; text-align: center; font-weight: bold;\"><td width=\"10px\">Clave</td><td width=\"150px\">Materia</td><td width=\"40px\">Fecha</td><td width=\"10px\">Periodo</td><td width=\"10px\">Forma Eval.</td><td width=\"10px\">Calificacion</td></tr><tr><td>R213</td><td align=\"left\">RELACIONES PUBLICAS</td><td>Jun 10 2011</td><td>11/2</td><td>ORD</td><td>10</td></tr><tr><td>R214</td><td align=\"left\">COSTOS DE COMERCIALIZACION</td><td>Dic 10 2010</td><td>11/1</td><td>ORD</td><td>8</td></tr><tr><td>R215</td><td align=\"left\">MEDIOS PUBLICITARIOS</td><td>Dic 10 2010</td><td>11/1</td><td>ORD</td><td>10</td></tr><tr><td>R216</td><td align=\"left\">SISTEMAS DE INFORMACION DE MERCADOTECNIA</td><td>Jun 10 2011</td><td>11/2</td><td>ORD</td><td>9</td></tr><tr><td>R217</td><td align=\"left\">INTRODUCCION A LA COMUNICACION INTEGRAL</td><td>Dic 10 2010</td><td>11/1</td><td>ORD</td><td>9</td></tr><tr><td>R218</td><td align=\"left\">COMPORTAMIENTO DEL CONSUMIDOR</td><td>Dic 10 2010</td><td>11/1</td><td>ORD</td><td>10</td></tr><tr><td>R219</td><td align=\"left\">INTRODUCCION A LA VENTA</td><td>Dic 10 2010</td><td>11/1</td><td>ORD</td><td>9</td></tr><tr><td>R220</td><td align=\"left\">ESTADISTICA APLICADA</td><td>Jun 10 2011</td><td>11/2</td><td>ORD</td><td>9</td></tr><tr><td>R221</td><td align=\"left\">TALLER DE MANEJO DE BASE DE DATOS</td><td>Jun 10 2011</td><td>11/2</td><td>ORD</td><td>10</td></tr><tr><td>R222</td><td align=\"left\">DERECHO MERCANTIL</td><td>Jun 10 2011</td><td>11/2</td><td>ORD</td><td>10</td></tr><tr><td>R223</td><td align=\"left\">METODO ESTADISTICO</td><td>Dic 10 2010</td><td>11/1</td><td>ORD</td><td>8</td></tr></tbody></table><br></center><style>\r\n" + 
				"			                  table.bottomBorder{background-color:WhiteSmoke;font-size:xx-small;text-align:center;border-collapse:collapse;}\r\n" + 
				"							  table.bottomBorder td {border-bottom: 1px solid TEAL;padding:1px;}\r\n" + 
				"							</style><center>\r\n" + 
				"								<table width=\"100%\" class=\"bottomBorder\"><tbody><tr><td colspan=\"6\" style=\"background-color: Maroon; font-size: x-small; font-weight: bold; color: White; text-align: center\">TERCER SEMESTRE</td></tr><tr style=\"background-color: WhiteSmoke; font-size: xx-small; text-align: center; font-weight: bold;\"><td width=\"10px\">Clave</td><td width=\"150px\">Materia</td><td width=\"40px\">Fecha</td><td width=\"10px\">Periodo</td><td width=\"10px\">Forma Eval.</td><td width=\"10px\">Calificacion</td></tr><tr><td>R324</td><td align=\"left\">INVESTIGACION DE MERCADOS CUANTITATIVA Y CUALITATIVA</td><td>Dic 16 2011</td><td>12/1</td><td>ORD</td><td>8</td></tr><tr><td>R325</td><td align=\"left\">MERCADOTECNIA ANALITICA</td><td>Dic 16 2011</td><td>12/1</td><td>ORD</td><td>8</td></tr><tr><td>R326</td><td align=\"left\">VENTA ESPECIALIZADA</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>10</td></tr><tr><td>R327</td><td align=\"left\">CREDITOS Y COBRANZAS</td><td>Dic 16 2011</td><td>12/1</td><td>ORD</td><td>8</td></tr><tr><td>R328</td><td align=\"left\">TECNICAS Y HABILIDADES DE VENTAS</td><td>Dic 16 2011</td><td>12/1</td><td>ORD</td><td>9</td></tr><tr><td>R329</td><td align=\"left\">TENDENCIAS ECONOMICAS GLOBALES</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>10</td></tr><tr><td>R330</td><td align=\"left\">MACROECONOMIA</td><td>Jun 10 2011</td><td>11/2</td><td>ORD</td><td>9</td></tr><tr><td>R335</td><td align=\"left\">MERCADOTECNIA POLITICA</td><td>Dic 16 2011</td><td>12/1</td><td>ORD</td><td>10</td></tr></tbody></table><br></center><style>\r\n" + 
				"			                  table.bottomBorder{background-color:WhiteSmoke;font-size:xx-small;text-align:center;border-collapse:collapse;}\r\n" + 
				"							  table.bottomBorder td {border-bottom: 1px solid TEAL;padding:1px;}\r\n" + 
				"							</style><center>\r\n" + 
				"								<table width=\"100%\" class=\"bottomBorder\"><tbody><tr><td colspan=\"6\" style=\"background-color: Maroon; font-size: x-small; font-weight: bold; color: White; text-align: center\">CUARTO SEMESTRE</td></tr><tr style=\"background-color: WhiteSmoke; font-size: xx-small; text-align: center; font-weight: bold;\"><td width=\"10px\">Clave</td><td width=\"150px\">Materia</td><td width=\"40px\">Fecha</td><td width=\"10px\">Periodo</td><td width=\"10px\">Forma Eval.</td><td width=\"10px\">Calificacion</td></tr><tr><td>R432</td><td align=\"left\">ESTUDIOS E INTERPRETACION DE ESTADOS FINANCIEROS</td><td>Dic 16 2012</td><td>13/1</td><td>ORD</td><td>10</td></tr><tr><td>R433</td><td align=\"left\">COMPRAS</td><td>Dic 16 2012</td><td>13/1</td><td>ORD</td><td>10</td></tr><tr><td>R434</td><td align=\"left\">MERCADOTECNIA DIRECTA</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>10</td></tr><tr><td>R435</td><td align=\"left\">CANALES DE DISTRIBUCION Y LOGISTICA</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>10</td></tr><tr><td>R436</td><td align=\"left\">MEDIOS PROMOCIONALES DE VENTA</td><td>Dic 16 2011</td><td>12/1</td><td>ORD</td><td>10</td></tr><tr><td>R437</td><td align=\"left\">APLICACIONES DE INFORMATICA COMERCIAL</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>8</td></tr><tr><td>R438</td><td align=\"left\">INVESTIGACION DE MERCADOS APLICADA</td><td>Dic 16 2012</td><td>13/1</td><td>ORD</td><td>9</td></tr><tr><td>R439</td><td align=\"left\">ADMINISTRACION DE VENTAS</td><td>Dic 16 2012</td><td>13/1</td><td>ORD</td><td>9</td></tr><tr><td>R443</td><td align=\"left\">MERCADOTECNIA ESTRATEGICA</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>10</td></tr><tr><td>R453</td><td align=\"left\">TALLER DE COMUNICACION INTEGRAL</td><td>Dic 16 2012</td><td>13/1</td><td>ORD</td><td>9</td></tr></tbody></table><br></center><style>\r\n" + 
				"			                  table.bottomBorder{background-color:WhiteSmoke;font-size:xx-small;text-align:center;border-collapse:collapse;}\r\n" + 
				"							  table.bottomBorder td {border-bottom: 1px solid TEAL;padding:1px;}\r\n" + 
				"							</style><center>\r\n" + 
				"								<table width=\"100%\" class=\"bottomBorder\"><tbody><tr><td colspan=\"6\" style=\"background-color: Maroon; font-size: x-small; font-weight: bold; color: White; text-align: center\">QUINTO SEMESTRE</td></tr><tr style=\"background-color: WhiteSmoke; font-size: xx-small; text-align: center; font-weight: bold;\"><td width=\"10px\">Clave</td><td width=\"150px\">Materia</td><td width=\"40px\">Fecha</td><td width=\"10px\">Periodo</td><td width=\"10px\">Forma Eval.</td><td width=\"10px\">Calificacion</td></tr><tr><td>R542</td><td align=\"left\">DIRECCION ESTRATEGICA COMERCIAL</td><td>Jun 26 2013</td><td>13/2</td><td>ORD</td><td>8</td></tr><tr><td>R543</td><td align=\"left\">PLANEACION ESTRATEGICA DE LA COMUNICACION INTEGRAL</td><td>Jun 26 2013</td><td>13/2</td><td>ORD</td><td>9</td></tr><tr><td>R544</td><td align=\"left\">PROYECTO DE INVESTIGACION APLICADA</td><td>Jun 26 2013</td><td>13/2</td><td>ORD</td><td>9</td></tr><tr><td>R545</td><td align=\"left\">ADMINISTRACION DE PRODUCTOS Y SERVICIOS</td><td>Jun 26 2013</td><td>13/2</td><td>ORD</td><td>9</td></tr><tr><td>R546</td><td align=\"left\">MEDICION Y DESARROLLO DE LOS MERCADOS</td><td>Jun 26 2013</td><td>13/2</td><td>ORD</td><td>9</td></tr><tr><td>R547</td><td align=\"left\">TALLER DE DESARROLLO DE NEGOCIOS</td><td>Dic 16 2012</td><td>13/1</td><td>ORD</td><td>10</td></tr><tr><td>R548</td><td align=\"left\">ELECTIVA</td><td>Jun 26 2012</td><td>12/2</td><td>ORD</td><td>10</td></tr><tr><td>R549</td><td align=\"left\">SERVICIO SOCIAL</td><td>Jun 20 2014</td><td>14/2</td><td>ORD</td><td>10</td></tr></tbody>\r\n" + 
				"								</table>\r\n" + 
				"								<br>\r\n" + 
				"							</center>\r\n" + 
				"						</span>\r\n" + 
				"    <br>\r\n" + 
				"    </div>\r\n" + 
				"\r\n" + 
				"</body></html>");
	}
	
}
